Update main-deployment.yml

diff --git a/.github/workflows/main-deployment.yml b/.github/workflows/main-deployment.yml
--- a/.github/workflows/main-deployment.yml
+++ b/.github/workflows/main-deployment.yml
@@ -19,6 +19,16 @@ jobs:
           ref: main
           fetch-depth: 0
 
+      - name: Extract Version from Commit Message
+        id: extract_version
+        run: |
+          VERSION=$(git log -1 --pretty=%B | grep -oP '(release|hotfix)/\K[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?' | head -n 1 | tr -d '[:space:]')
+          if [ -z "$VERSION" ]; then
+          echo "Version not found in commit message."
+          exit 1
+          fi
+          echo "VER=$VERSION" >> $GITHUB_ENV
+
       - name: Check If Release Branch Exists in Other Repo
         id: check_branch_exists
         env:
@@ -32,17 +42,7 @@ jobs:
           else
             echo "Release branch 'release/${VER}' does not exist in the other repository."
             echo "CREATE_EMPTY_RELEASE=true" >> $GITHUB_ENV
-          fi
-
-      - name: Extract Version from Commit Message
-        id: extract_version
-        run: |
-          VERSION=$(git log -1 --pretty=%B | grep -oP '(release|hotfix)/\K[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?' | head -n 1 | tr -d '[:space:]')
-          if [ -z "$VERSION" ]; then
-          echo "Version not found in commit message."
-          exit 1
-          fi
-          echo "VER=$VERSION" >> $GITHUB_ENV
+          fi          
           
       - name: Fetch Latest Release Branch SHA
         if: env.CREATE_EMPTY_RELEASE == 'true'
